runtime: go
api_version: go1

handlers:
- url: /
  static_files: index.html
  upload: index.html
- url: /favicon.png
  static_files: favicon.png
  upload: favicon.png
- url: /robots.txt
  static_files: robots.txt
  upload: robots.txt
- url: /sitemap.xml
  static_files: sitemap.xml
  upload: sitemap.xml

- url: /cron
  script: _go_app
  login: admin
- url: /.*
  script: _go_app
